- hosts: all
  sudo: True

  vars:
    keystone_init:
      OS_SERVICE_TOKEN: password
      OS_SERVICE_ENDPOINT: http://localhost:35357/v2.0
    keystone_admin:
      OS_TENANT_NAME: admin
      OS_USERNAME: admin
      OS_PASSWORD: password
      OS_AUTH_URL: http://localhost:35357/v2.0

  tasks:
  - apt: update_cache=yes upgrade=yes
  - apt: name=mysql-server state=present
  - apt: name=mysql-client state=present
  - apt: name=python-mysqldb state=present
  - apt: name=expect state=present
  - copy: src=files/my.cnf dest=/etc/my.cnf
  - service: name=mysql state=restarted enabled=yes
  - copy: src=files/mysql_secure_installation.sh
          dest=/root/mysql_secure_installation.sh
          mode=0755
  - command: /root/mysql_secure_installation.sh
             creates=/tmp/mysql_secure_installation.done
  - copy: src=files/client.my.cnf dest=/root/.my.cnf

  - mysql_db: name=keystone state=absent
  - mysql_db: name=keystone state=present
  - mysql_user: name=keystone password=password host=localhost priv=keystone.*:ALL state=present
  - mysql_user: name=keysotne password=password host=% priv=keystone.*:ALL state=present

  - apt: name=keystone state=present
  - apt: name=python-keystoneclient state=present
  - command: keystone-manage pki_setup --keystone-user keystone --keystone-group keystone
             creates=/etc/keystone/ssl/certs/01.pem
  - file: path=/etc/keystone/ssl owner=keystone group=keystone mode=750 state=directory recurse=yes
  - file: path=/var/log/keystone owner=keystone group=keystone mode=750 state=directory recurse=yes

  - ini_file: dest=/etc/keystone/keystone.conf
              section=DEFAULT
              option=admin_token
              value=password

  - ini_file: dest=/etc/keystone/keystone.conf
              section=database
              option=connection
              value=mysql://keystone:password@localhost/keystone

  - ini_file: dest=/etc/keystone/keystone.conf
              section=DEFAULT
              option=verbose
              value=True

  - ini_file: dest=/etc/keystone/keystone.conf
              section=DEFAULT
              option=debug
              value=True

  - ini_file: dest=/etc/keystone/keystone.conf
              section=DEFAULT
              option=log_dir
              value=/var/log/keystone

  - ini_file: dest=/etc/keystone/keystone.conf
              section=DEFAULT
              option=log_file
              value=keystone.log

  - command: su -s /bin/sh -c "keystone-manage db_sync" keystone
  - service: name=keystone state=restarted enabled=yes

  - wait_for: port=35357 delay=10

  - shell: keystone tenant-create --name admin --description "Admin Tenant"
    environment: keystone_init
  - shell: keystone user-create --name admin --pass password
    environment: keystone_init
  - shell: keystone role-create --name admin
    environment: keystone_init
  - shell: keystone user-role-add --tenant admin --user admin --role admin
    environment: keystone_init
  - shell: keystone tenant-create --name service --description "Service Tenant"
    environment: keystone_init
  - shell: keystone service-create --name keystone --type identity --description "OpenStack Identity"
    environment: keystone_init
  - shell: keystone endpoint-create --service-id $(keystone service-list | awk '/ identity / {print $2}') --publicurl http://localhost:5000/v2.0 --internalurl http://localhost:5000/v2.0 --adminurl http://localhost:35357/v2.0 --region regionOne
    environment: keystone_init
  - shell: keystone tenant-create --name tenant1
    environment: keystone_init
  - shell: keystone user-create --name user1 --pass password --tenant tenant1
    environment: keystone_init

  - copy: src=files/openrc dest=/home/vagrant/openrc owner=vagrant group=users mode=0644
  - copy: src=files/openrc.tenant1 dest=/home/vagrant/openrc.tenant1 owner=vagrant group=users mode=0644
