# -*- mode: ruby -*-
# vi: set ft=ruby :

# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

BOX = "chef/centos-7.0"

Vagrant.configure(2) do |config|
  config.vm.box = BOX
  config.vm.synced_folder '.', '/vagrant', disabled: true
  config.vm.provider "virtualbox" do |vb|
    vb.customize ["modifyvm", :id, "--memory", "2048"]
    vb.customize ["modifyvm", :id, "--cpus", "2"]
  end
  config.ssh.shell = "bash -c 'BASH_ENV=/etc/profile exec bash'"
  if Vagrant.has_plugin?("vagrant-hostmanager")
    config.hostmanager.enabled = true
    config.hostmanager.manage_host = true
    config.hostmanager.ignore_private_ip = false
    config.hostmanager.include_offline = true
  end
  if Vagrant.has_plugin?("vagrant-cachier")
    config.cache.scope = :box
  end
  config.vm.define "node001", primary: true do |node|
    node.vm.hostname= "node001"
    node.vm.network :private_network, ip: '10.0.20.100'
    node.vm.network :private_network, ip: '10.0.20.101'
    node.vm.network :private_network, ip: '10.0.20.102'
    node.vm.network :private_network, ip: '10.0.20.103'
  end
  config.vm.define "node002", primary: true do |node|
    node.vm.hostname= "node002"
    node.vm.network :private_network, ip: '10.0.20.110'
    node.vm.network :private_network, ip: '10.0.20.111'
    node.vm.network :private_network, ip: '10.0.20.112'
    node.vm.network :private_network, ip: '10.0.20.113'
  end
  config.vm.define "node003", primary: true do |node|
    node.vm.hostname= "node003"
    node.vm.network :private_network, ip: '10.0.20.120'
    node.vm.network :private_network, ip: '10.0.20.121'
    node.vm.network :private_network, ip: '10.0.20.122'
    node.vm.network :private_network, ip: '10.0.20.123'
  end
  config.vm.define "node004", primary: true do |node|
    node.vm.hostname= "node004"
    node.vm.network :private_network, ip: '10.0.20.130'
    node.vm.network :private_network, ip: '10.0.20.131'
    node.vm.network :private_network, ip: '10.0.20.132'
    node.vm.network :private_network, ip: '10.0.20.133'
  end
end
