# -*- mode: ruby -*-
# vi: set ft=ruby :

# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

Vagrant.configure(2) do |config|
  config.vm.box = 'ubuntu/trusty64'
  config.ssh.shell = "bash -c 'BASH_ENV=/etc/profile exec bash'"
  config.cache.scope = :box if Vagrant.has_plugin?('vagrant-cachier')
  config.vm.provider 'virtualbox' do |vb|
    vb.customize ['modifyvm', :id, '--memory', 1024]
    vb.customize ['modifyvm', :id, '--cpus', 1]
  end
  config.vm.hostname = 'osclients'
  config.vm.provision "shell", inline: $shell
end

$shell = <<-CONTENTS
export DEBIAN_FRONTEND=noninteractive
apt-get update && apt-get upgrade -y
apt-get install -y python-dev python-pip
projects=https://raw.githubusercontent.com/openstack/governance/master/reference/projects.yaml
for client in $(curl -s $projects | grep 'repo:.*/python-.*client' | cut -d / -f 2); do
    apt-get install -y $client
done
CONTENTS
