# -*- mode: ruby -*-
# vi: set ft=ruby :

# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

BOX = "chef/centos-7.0"
BRIDGE = "tap0"

Vagrant.configure(2) do |config|
  config.vm.box = BOX
  config.vm.provider "virtualbox" do |vb|
    vb.customize ["modifyvm", :id, "--memory", "8192"]
    vb.customize ["modifyvm", :id, "--cpus", "4"]
  end
  if Vagrant.has_plugin?("vagrant-hostmanager")
    config.hostmanager.enabled = true
    config.hostmanager.manage_host = true
    config.hostmanager.ignore_private_ip = false
    config.hostmanager.include_offline = true
  end
  config.vm.synced_folder '.', '/vagrant', disabled: true
  config.vm.define "compute001" do |node|
    node.vm.hostname= "compute001"
    node.vm.network :public_network, ip: '10.100.50.20', netmask: '255.255.0.0', bridge: BRIDGE
    node.vm.provision "ansible" do |ansible|
      ansible.playbook = "playbook.yaml"
    end
  end
  config.vm.define "compute002" do |node|
    node.vm.hostname= "compute002"
    node.vm.network :public_network, ip: '10.100.50.21', netmask: '255.255.0.0', bridge: BRIDGE
    node.vm.provision "ansible" do |ansible|
      ansible.playbook = "playbook.yaml"
    end
  end
  config.vm.define "network" do |node|
    node.vm.hostname= "network"
    node.vm.network :public_network, ip: '10.100.50.30', netmask: '255.255.0.0', bridge: BRIDGE
    node.vm.provision "ansible" do |ansible|
      ansible.playbook = "playbook.yaml"
    end
  end
  config.vm.define "storage" do |node|
    node.vm.hostname= "storage"
    node.vm.network :public_network, ip: '10.100.50.40', netmask: '255.255.0.0', bridge: BRIDGE
    node.vm.provision "ansible" do |ansible|
      ansible.playbook = "playbook.yaml"
    end
  end
  config.vm.define "filer" do |node|
    node.ssh.shell = "bash -c 'BASH_ENV=/etc/profile exec bash'"
    node.vm.box = 'ubuntu/trusty64'
    node.vm.hostname= "filer"
    node.vm.network :public_network, ip: '10.100.50.41', netmask: '255.255.0.0', bridge: BRIDGE
    node.vm.provision "ansible" do |ansible|
      ansible.playbook = "playbook.yaml"
    end
    node.vm.provider "virtualbox" do |vb|
      vb.customize ['createhd', '--filename', 'dcd3ac98.vdi', '--size', 65536]
      vb.customize ['storageattach', :id, '--storagectl', 'SATAController', '--port', 1, '--device', 0, '--type', 'hdd', '--medium', 'dcd3ac98.vdi']
    end
  end
  config.vm.define "shared" do |node|
    node.vm.hostname= "shared"
    node.vm.network :public_network, ip: '10.100.50.50', netmask: '255.255.0.0', bridge: BRIDGE
    node.vm.provision "ansible" do |ansible|
      ansible.playbook = "playbook.yaml"
    end
  end
  config.vm.define "controller", primary: true do |node|
    node.vm.hostname= "controller"
    node.vm.network :public_network, ip: '10.100.50.10', netmask: '255.255.0.0', bridge: BRIDGE
    node.vm.provision "ansible" do |ansible|
      ansible.playbook = "playbook.yaml"
    end
    node.vm.provider "virtualbox" do |vb|
      vb.customize ["modifyvm", :id, "--memory", "16384"]
      vb.customize ["modifyvm", :id, "--cpus", "4"]
    end
    node.vm.provider "virtualbox" do |vb|
      vb.customize ['createhd', '--filename', 'e7a31749.vdi', '--size', 65536]
      vb.customize ['storageattach', :id, '--storagectl', 'IDE Controller', '--port', 1, '--device', 0, '--type', 'hdd', '--medium', 'e7a31749.vdi']
      vb.customize ['createhd', '--filename', '7dcc603c.vdi', '--size', 65536]
      vb.customize ['storageattach', :id, '--storagectl', 'IDE Controller', '--port', 1, '--device', 1, '--type', 'hdd', '--medium', '7dcc603c.vdi']
    end
  end
end
