# -*- mode: ruby -*-
# vi: set ft=ruby :

# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

require 'yaml'
CONFIG = YAML.load(File.open(File.join(File.dirname(__FILE__), "config.yaml"), File::RDONLY).read)

def add_block_device(node, id, size)
  node.vm.provider "virtualbox" do |vb|
    vb.customize ['createhd', '--filename', "#{node.vm.hostname}_#{id}.vdi", '--size', size]
    vb.customize ['storageattach', :id, '--storagectl', 'IDE Controller', '--port', 1, '--device', id, '--type', 'hdd', '--medium', "#{node.vm.hostname}_#{id}.vdi"]
  end
end

Vagrant.configure(2) do |config|
  config.vm.box = CONFIG['box']
  config.vm.synced_folder '.', '/vagrant', disabled: true
  config.vm.provider "virtualbox" do |vb|
    vb.customize ["modifyvm", :id, "--memory", CONFIG['resources']['memory']]
    vb.customize ["modifyvm", :id, "--cpus", CONFIG['resources']['vcpus']]
  end

  CONFIG['address']['compute'].each_with_index do |address, index|
    name = "node#{index + 1}"
    config.vm.define name do |node|
      node.vm.hostname= name
      node.vm.network :public_network, ip: address, netmask: CONFIG['netmask'], bridge: CONFIG['bridge']
      node.vm.provision "ansible" do |ansible|
        ansible.playbook = "playbook.yaml"
      end
    end
  end

  ['network', 'storage', 'shared'].each do |name|
    config.vm.define name do |node|
      node.vm.hostname = name
      node.vm.network :public_network, ip: CONFIG['address'][name], netmask: CONFIG['netmask'], bridge: CONFIG['bridge']
      node.vm.provision "ansible" do |ansible|
        ansible.playbook = "playbook.yaml"
      end
    end
  end

  config.vm.define "filer" do |node|
    node.vm.hostname= "filer"
    node.vm.network :public_network, ip: CONFIG['address']['filer'], netmask: CONFIG['netmask'], bridge: CONFIG['bridge']
    node.vm.provision "ansible" do |ansible|
      ansible.playbook = "playbook.yaml"
    end
    add_block_device(node, 0, CONFIG['resources']['storage'])
  end

  config.vm.define "controller", primary: true do |node|
    node.vm.hostname= "controller"
    node.vm.network :public_network, ip: CONFIG['address']['controller'], netmask: CONFIG['netmask'], bridge: CONFIG['bridge']
    node.vm.provision "ansible" do |ansible|
      ansible.playbook = "playbook.yaml"
    end
    node.vm.provider "virtualbox" do |vb|
      vb.customize ["modifyvm", :id, "--memory", (CONFIG['resources']['memory'] * 2)]
      vb.customize ["modifyvm", :id, "--cpus", (CONFIG['resources']['vcpus'] * 2)]
    end
    add_block_device(node, 0, CONFIG['resources']['storage'])
    add_block_device(node, 1, CONFIG['resources']['storage'])
  end

end
