---
box: ubuntu/trusty64
password: password
networking:
  bridge: wlp3s0
  netmask: 255.255.0.0
  address: 10.100.60.10
resources:
  memory: 4096
  vcpus: 2
  storage: 65536
components:
  aodh: false
  ceilometer: false
  ceph: false
  cloudkitty: false
  gnocchi: false
  heat: false
  rally: false
  swift: false
  tempest: false
  trove: false
  mistral: false
