# -*- mode: ruby -*-
# vi: set ft=ruby :

# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

require 'yaml'

unless defined? CONFIG
  configuration_file = File.join(File.dirname(__FILE__), 'config.yaml')
  CONFIG = YAML.load(File.open(configuration_file, File::RDONLY).read)
end

Vagrant.configure(2) do |config|
  config.vm.box = CONFIG['box']
  config.vm.synced_folder '.', '/vagrant', disabled: true
  config.ssh.shell = "bash -c 'BASH_ENV=/etc/profile exec bash'"
  config.cache.scope = :box if Vagrant.has_plugin?('vagrant-cachier')
  config.vm.provider 'virtualbox' do |vb|
    vb.customize ['modifyvm', :id, '--memory', CONFIG['resources']['memory']]
    vb.customize ['modifyvm', :id, '--cpus', CONFIG['resources']['vcpus']]
    vb.customize ['modifyvm', :id, '--pagefusion', 'on']
    vb.customize ['modifyvm', :id, '--largepages', 'on']
    vb.customize ['modifyvm', :id, '--pae', 'off']
  end
  config.vm.define 'devstack', primary: true do |node|
    node.vm.hostname = 'devstack'
    node.vm.provision 'ansible' do |ansible|
      ansible.playbook = 'playbook.yaml'
      ansible.verbose = 'v'
    end
    node.vm.provision 'shell',
                      inline: 'cd /home/vagrant/devstack && ./stack.sh',
                      privileged: false,
                      keep_color: true
    node.vm.network :public_network,
                    ip: CONFIG['networking']['address'],
                    netmask: CONFIG['networking']['netmask'],
                    bridge: CONFIG['networking']['bridge']
  end
end
